### PR TITLE
Fixed issue with undefined flyfile

### LINKED ISSUE #192: Not very informative message, when flyfile.js not found
The problem is with `cli.spawn` method, that not handle `null` exception.
Fly instance should emit `flyfile_not_found` event to properly show error message.

Btw, fixing it. Gonna submit PR later in the evening.

### PR DESCRIPTION
**Pull request by hzlmn**
Fixes #192 
@lukeed

### CODE REVIEW

File: lib/reporter.js [hunk 1]
```diff
@@ -14,9 +14,9 @@ module.exports = function () {
 			log('Flying with ' + fmt.path + '...', obj.path)
 		})
 
-		.on('flyfile_not_found', function (obj) {
+		.on('flyfile_not_found', function () {
 			process.exitCode = 1
-			log('No Flyfile Error: ' + fmt.error, obj.error)
+			log('Could not find flyfile in current directory')
```
Comment (lukeed) [inline lib/reporter.js]: Message isn't quite right. `utils.read` will [traverse upwards](https://www.npmjs.com/package/find-up) looking for a flyfile.

File: lib/fly.js [hunk 2]
```diff
@@ -42,9 +41,6 @@ function Fly(options) {
 
 	// attach files & funcs into the curr instance
 	assign(self, {
-		file: file,
-		plugins: plugins,
```
Comment (lukeed) [inline lib/fly.js:46]: Why do we need to remove `plugins` and `root` from the self assign here?

File: lib/index.js [hunk 3]
```diff
@@ -21,12 +21,16 @@ co(function * () {
...
 	} else {
 		var fly = yield cli.spawn(opts.file)
+		reporter.call(fly)
 
 		if (opts.list) {
 			cli.list(fly.host, {bare: opts.list === 'bare'})
 		} else {
-			return reporter.call(fly)
-				.emit('fly_run', {path: fly.file})
+			if (!fly.file) {
```
Comment (lukeed) [inline lib/index.js]: You can move the `!fly.file` check ahead of the `if-else` check. The `list` option still requires a flyfile to be read & present.

File: lib/fly.js [hunk 4]
```diff
@@ -61,6 +57,14 @@ function Fly(options) {
 		}, {})
 	})
 
+	if (!file) {
```
Comment (lukeed) [inline lib/fly.js:60]: This can go higher---directly after the `var file` declaration

Comment (hzlmn) [inline lib/fly.js:60]: If we declare it higher tests will fail because we did not assign default params like _.filters and so on.

File: lib/fly.js (hunk 2 above)
Comment (hzlmn) [inline lib/fly.js:46]: Because we got `file = undefined` and then try to `path.dirname(*undefined*)` that throws an exception. And when we are sure that file been defined we assign these props below.
I was thinking about more elegant solution, but did not want to change defined architecture

File: lib/reporter.js (hunk 1 above)
Comment (hzlmn) [inline lib/reporter.js]: Got it.

File: lib/fly.js (hunk 4 above)
Comment (lukeed) [inline lib/fly.js:60]: Gotcha

**Comment by lukeed** [comment]
@hzlmn When you get a chance to make those minor adjustments (the ones that are possible), I'll get this in 👍

**Comment by lukeed** [comment]
And let's contain this PR just to what's already been done. If you continue to tackle #181, it should be its own PR.

Thanks!

**Comment by hzlmn** [comment]
@lukeed ok, I gonna submit updates when i will be at home

**Comment by hzlmn** [comment]
@lukeed updated, sorry for late response

**Comment by lukeed** [comment]
@hzlmn there's no deadline!

**Comment by lukeed** [comment]
You the man @hzlmn, thank you 🎉
